import Head from 'next/head'
import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import TitleBar from '../components/TitleBar.js';
import TileGrid from '../components/TileGrid.js';
import Footer from '../components/Footer.js';
import PlanningIdea from '../components/PlanningIdea.js';
import { useState, createContext, useContext } from 'react'
// import MyDialog from '../components/Dialog.js';


export default function App() {
  // return( <></> ) 
  const [count, setCount] = useState( 0 );
  const [list, setList] = useState( {} );
  const [grid, setGrid] = useState( {} );
  // const [init, setInit] = useState( 0 );
  // var selections = {};

  let x = []
  for (var i = 0; i < 5; i++) {
    x.push(new PlanningIdea('######', 'xxxxxxxxxx', 'x', 'x'))
  }
  let y = []
  for (var i = 0; i < 3; i++) {
    y.push(new PlanningIdea('######', 'xxxxxxxxxx', 'x', 'x'))
  }
  let z = []
  for (var i = 0; i < 6; i++) {
    z.push(new PlanningIdea('######', 'xxxxxxxxxx', 'x', 'x'))
  }

  return (
    // <div classNameName="App">
    //   <header classNameName="App-header">
    //     <img src={logo} classNameName="App-logo" alt="logo" />
    //     <p>
    //       Edit <code>src/App.js</code> and save to reload.
    //     </p>
    //     <a
    //       classNameName="App-link"
    //       href="https://reactjs.org"
    //       target="_blank"
    //       rel="noopener noreferrer"
    //     >
    //       Learn React
    //     </a>
    //   </header>
    // </div>
    <UserContext.Provider value={{count, setCount, list, setList, grid, setGrid}}>
      <div>
        {/* <MyDialog /> */}
        <TitleBar />
        <div className="pb-20">
        <TileGrid title="Category 1" rec="3" arr={x}/>
        <TileGrid title="Category 2" rec="7" arr={y}/>
        <TileGrid title="Category 3" rec="2" arr={z}/>
        </div>
        <Footer />
        
      </div>
    </UserContext.Provider>



  );
}

export const UserContext = createContext();
// export default App;


// export default function Home() {
//   return (
//     <div classNameName={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main classNameName={styles.main}>
//         <h1 classNameName={styles.title}>
//           Welcome to <a href="https://nextjs.org">Next.js!</a>
//         </h1>

//         <p classNameName={styles.description}>
//           Get started by editing{' '}
//           <code classNameName={styles.code}>pages/index.js</code>
//         </p>

//         <div classNameName={styles.grid}>
//           <a href="https://nextjs.org/docs" classNameName={styles.card}>
//             <h2>Documentation &rarr;</h2>
//             <p>Find in-depth information about Next.js features and API.</p>
//           </a>

//           <a href="https://nextjs.org/learn" classNameName={styles.card}>
//             <h2>Learn &rarr;</h2>
//             <p>Learn about Next.js in an interactive course with quizzes!</p>
//           </a>

//           <a
//             href="https://github.com/vercel/next.js/tree/canary/examples"
//             classNameName={styles.card}
//           >
//             <h2>Examples &rarr;</h2>
//             <p>Discover and deploy boilerplate example Next.js projects.</p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             classNameName={styles.card}
//           >
//             <h2>Deploy &rarr;</h2>
//             <p>
//               Instantly deploy your Next.js site to a public URL with Vercel.
//             </p>
//           </a>
//         </div>
//       </main>

//       <footer classNameName={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{' '}
//           <span classNameName={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   )
// }
